before:
  hooks:
    - go mod tidy
dist: build
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
archives:
  - format: binary
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
nfpms:
  - package_name: birdwatcher
    homepage: https://github.com/skoef/birdwatcher
    maintainer: "Reinier Schoof <reinier@skoef.nl>"
    description: healthchecker for BIRD-anycasted services
    license: MIT
    bindir: /usr/sbin
    contents:
      - src: dist/systemd/birdwatcher.service
        dst: /lib/systemd/system/birdwatcher.service
        packager: deb
        file_info:
          owner: root
          group: root
          mode: 0644
      - src: dist/systemd/birdwatcher.service
        dst: /usr/lib/systemd/system/birdwatcher.service
        packager: rpm
        file_info:
          owner: root
          group: root
          mode: 0644
      - src: dist/birdwatcher.conf
        dst: /etc/birdwatcher.conf
        type: config|noreplace
        file_info:
          owner: root
          group: root
          mode: 0644
    formats:
      - deb
      - rpm
    overrides:
      deb:
        dependencies:
        - libc6
      rpm:
        dependencies:
        - glibc
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^Merge pull request'
      - '^Merge branch'
